// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$.D1YvAgfNMpADhpy8WwSdu.1avdqtUv1p/nGrA/bn2od6K/yIQN2.",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$y8PTZhcRkmKq1m1iL/AgjOKBD9DTnUNLbFnXcJLwYxfY0UECQh9TG",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "priya.prabhu@nexacore.com",
                            FirstName = "Priya",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Prabhu",
                            Phone = "9876543210",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Marketing Executive",
                            Email = "arjun.sharma@nexacore.com",
                            FirstName = "Arjun",
                            JoinDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Sharma",
                            Phone = "9123456780",
                            Salary = 630000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "neha.kapoor@nexacore.com",
                            FirstName = "Neha",
                            JoinDate = new DateTime(2019, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kapoor",
                            Phone = "9988776655",
                            Salary = 550000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2019, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "rahul.varma@nexacore.com",
                            FirstName = "Rahul",
                            JoinDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Varma",
                            Phone = "9870123456",
                            Salary = 730000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "sneha.prasad@nexacore.com",
                            FirstName = "Sneha",
                            JoinDate = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Prasad",
                            Phone = "9765432100",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2017, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Senior Developer",
                            Email = "vikram.raj@nexacore.com",
                            FirstName = "Vikram",
                            JoinDate = new DateTime(2017, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Raj",
                            Phone = "9654321098",
                            Salary = 1100000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2017, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Content Strategist",
                            Email = "ananya.singh@nexacore.com",
                            FirstName = "Ananya",
                            JoinDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Singh",
                            Phone = "9543210987",
                            Salary = 580000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Accounts Manager",
                            Email = "karthik.rajan@nexacore.com",
                            FirstName = "Karthik",
                            JoinDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Rajan",
                            Phone = "9432109876",
                            Salary = 800000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "DevOps Engineer",
                            Email = "pooja.ghosh@nexacore.com",
                            FirstName = "Pooja",
                            JoinDate = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Ghosh",
                            Phone = "9321098765",
                            Salary = 920000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Supply Chain Analyst",
                            Email = "amit.joshi@nexacore.com",
                            FirstName = "Amit",
                            JoinDate = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Joshi",
                            Phone = "9210987654",
                            Salary = 670000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Brand Manager",
                            Email = "lakshmi.chandran@nexacore.com",
                            FirstName = "Lakshmi",
                            JoinDate = new DateTime(2022, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Chandran",
                            Phone = "9109876543",
                            Salary = 750000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2022, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2016, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Tax Consultant",
                            Email = "suresh.babu@nexacore.com",
                            FirstName = "Suresh",
                            JoinDate = new DateTime(2016, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Babu",
                            Phone = "9098765432",
                            Salary = 870000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2016, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "QA Engineer",
                            Email = "meera.krishnan@nexacore.com",
                            FirstName = "Meera",
                            JoinDate = new DateTime(2020, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Krishnan",
                            Phone = "9087654321",
                            Salary = 720000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Manager",
                            Email = "rohan.mehta@nexacore.com",
                            FirstName = "Rohan",
                            JoinDate = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Mehta",
                            Phone = "9876012345",
                            Salary = 880000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Logistics Coordinator",
                            Email = "divya.nair@nexacore.com",
                            FirstName = "Divya",
                            JoinDate = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Nair",
                            Phone = "9765012345",
                            Salary = 610000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
